#!/bin/bash

NAM=$1; shift
OUTDIR=$1; shift
INFILE=$1
mbc=$2
BED=/mnt/NGSF001/analysis/references/human/hg38/agilent_sureselect_human_all_exon_v8_hg38/S33266340_Padded.bed

export JAVA_TOOL_OPTIONS=-Xmx14g

~/src/AGeNT_2.0.5/agent/agent.sh -p -Xmx14g locatit -U -v2Hybrid -q 0 -K -C -R -IB -OB -l $BED -d 1 -X $PWD -o ${NAM} $INFILE 

### EOF ###
