#!/bin/bash

#SBATCH --job-name=strelka
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=1:30:00
#SBATCH --mem=6G

set -eux

PATH=/home/sah346/anaconda3/envs/strelka/bin:$PATH

THREADS=8

NAME=$1; shift
#BAM="$@"
NOR=$1; shift
TUM=$1
WORKDIR=/globalhome/sah346/HPC/cluster/projects/20-1LICH-001/strelka/august-2021

cd ${WORKDIR}

rm -rf ${WORKDIR}/${NAME}_strelka

configureStrelkaSomaticWorkflow.py --referenceFasta ~/NGSF001/analysis/references/human/gencode-30/GRCh38.primary_assembly.genome.fa \
    --normalBam $NOR \
    --tumorBam $TUM \
    --runDir ${WORKDIR}/${NAME}_strelka \
    --exome \
    --callRegions /globalhome/sah346/HPC/NGSF001/analysis/references/human/hg38/agilent_sureselect_human_all_exon_v8_hg38/S33266340_Covered.noheader.noAlt.bed.bgz
    #--callRegions ~/NGSF001/analysis/references/human/hg38/agilent_sureselect_human_all_exon_V7_hg38/S31285117_Padded.noHead.bed.bgz

${WORKDIR}/${NAME}_strelka/runWorkflow.py -m local -j ${THREADS}

### EOF ###
